Add amethyst `0.9` release blog post
amethyst/website-legacy pull request #111
Opened 2018-10-21 22:19 UTC by LucioFranco

2018-10-22 14:31 UTC, Xaeroxe approved these changes
Looks great!

2018-10-22 14:44 UTC, LucioFranco commented
Waiting for the release to go out before this gets merged.

2018-10-22 14:46 UTC, Moxinilian requested changes
I have yet to review this, and I also require a review from @gardrek.

2018-10-22 14:55 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +After about 2 months since the last release, version `0.9` of the Amethyst engine is now released on [crates.io](https://crates.io/crates/amethyst)! Due to the length of the contributor list, it will
```suggestion
It has been 2 months since the last release, and we are proud to announce that version `0.9` of the Amethyst game engine is now available on [crates.io](https://crates.io/crates/amethyst)! We would like to thank the numerous contributors involved in this release, the full list is available below.
```

2018-10-22 14:55 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +
```suggestion
We are also introducing new usability features for drawing in a 2D world. One of them is that you can now load spritesheets directly from files with the serde-compatible RON data format, making it very easy to load big spritesheets and convert them from other file formats.
```
The wording isn't great, but that's an idea that we forgot to mention.

2018-10-22 14:55 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +*   @fletcher
Maybe sort these alphabetically?

2018-10-22 15:07 UTC, LucioFranco commented on src/content/blog/release-0.9.md
> +*   @fletcher
You wanna do it? cuz I dont

2018-10-22 15:24 UTC, NaakkaDev commented on src/content/blog/release-0.9.md
> +With `0.9`, we have started building a new networking system. The initial work was to implement some basic features on top of UDP. You can see that work [here]( [https://github.com/amethyst/laminar](
`You can see that work [here]( [https://github.com/amethyst/laminar](https://github.com/amethyst/laminar)).` This doesn't look right?

2018-10-22 15:28 UTC, Temeez commented on src/content/blog/release-0.9.md
> +For a full list of changes, see [this changelog file]([https://github.com/amethyst/amethyst/blob/master/docs/CHANGELOG.md](https://github.com/amethyst/amethyst/blob/master/docs/CHANGELOG.md))
Is this link format correct? :thinking:

2018-10-22 16:21 UTC, torkleyy reviewed
Here my slightly delayed review, gonna blame GitHub.

2018-10-22 16:21 UTC, torkleyy commented on src/content/blog/release-0.9.md
> +
Too much space ^^

2018-10-22 16:21 UTC, torkleyy commented on src/content/blog/release-0.9.md
> +*   Added `shadow_update` and `shadow_fixed_update` functions to `State` so it stays updated even when paused.
This doesn't look like a single space

2018-10-22 16:21 UTC, torkleyy commented on src/content/blog/release-0.9.md
> +The first editor being built by the community is [randomPoison/amethyst-editor],
Missing link

2018-10-22 16:21 UTC, torkleyy commented on src/content/blog/release-0.9.md
> +[100 000 sprites at 60 fps was even confirmed possible!]([https://github.com/cart/amethyst-bunnymark](https://github.com/cart/amethyst-bunnymark))
Would be really awesome to show some comparision here, maybe even graphical (graphs :heart: ).

2018-10-22 16:33 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +The first editor being built by the community is [randomPoison/amethyst-editor],
I think it's referenced below.

2018-10-22 16:40 UTC, torkleyy commented on src/content/blog/release-0.9.md
> +The first editor being built by the community is [randomPoison/amethyst-editor],
Well, if I found it there I wouldn't have added the comment.

2018-10-22 16:43 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +The first editor being built by the community is [randomPoison/amethyst-editor],
Ah right, I made the same mistake

2018-10-22 18:51 UTC, distransient commented on src/content/blog/release-0.9.md
> +
Change to "One of them is **the ability to** load..."

2018-10-22 19:06 UTC, Rhuagh commented on src/content/blog/release-0.9.md
> +With `0.9`, we have started building a new networking system. The initial work was to implement some basic features on top of UDP. You can see that work [here]( [https://github.com/amethyst/laminar](
No, this is wrong indeed. `[here](link)` will become `<a href="link">here</a>`.

2018-10-22 19:07 UTC, Rhuagh commented
Many of the links are broken. `[]([]()]` should be `[]()`.

2018-10-22 21:48 UTC, gardrek commented on src/content/blog/release-0.9.md
> +which is being build with [Electron]. It currently has support for displaying
Replace this first sentence with:
`The first editor being built by the community is [randomPoison/amethyst-editor],
and it is being built with [Electron].`

2018-10-22 21:52 UTC, randomPoison requested changes
One minor request changing the phrasing of my own section, sorry for the last minute review!

2018-10-22 21:52 UTC, randomPoison commented on src/content/blog/release-0.9.md
> +we can determine which technology to use to build the official editor.
The last sentence here is a bit awkward (my fault, sorry 😓), could be better phrased as:

> This is being built way that makes it possible to experiment with multiple different editors without committing to one technology. This will allow us to get practical experience with a variety of GUI technologies so that we can eventually make an informed decision on which one to adopt for the official editor.

2018-10-22 21:53 UTC, gardrek commented on src/content/blog/release-0.9.md
> +*   The `DestroyAtTime` and `DestroyInTime` components allow destroying entities in a future point in time. The first one specifies the exact time in seconds where the entity should be destroy, and t
should be:
The `DestroyAtTime` and `DestroyInTime` components allow destroying entities at a future point in time. The first one specifies the exact time in seconds at which the entity should be destroyed, and the second one specifies a "time to live" duration.

2018-10-22 21:54 UTC, gardrek commented on src/content/blog/release-0.9.md
> +*   The `DestroyAtTime` and `DestroyInTime` components allow destroying entities in a future point in time. The first one specifies the exact time in seconds where the entity should be destroy, and t
Also, should maybe explain "time to live" sincee it's not obvious what that means.

2018-10-22 21:56 UTC, gardrek commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
```suggestion
*   glTF scenes no longer have materials swapped around.
```

2018-10-22 21:56 UTC, gardrek commented on src/content/blog/release-0.9.md
> +*   Support for progressive Jpeg loading was added.
```suggestion
*   Support for progressive JPEG loading was added.
```

2018-10-22 21:57 UTC, gardrek commented on src/content/blog/release-0.9.md
> +*   Ui coordinates now go from bottom to top.
```suggestion
*   UI coordinates now go from bottom to top.
```

2018-10-22 22:01 UTC, gardrek commented on src/content/blog/release-0.9.md
> +As well as to everyone who reviewed pull requests, opened issues, participated to the design discussions and requested features!
```suggestion
As well as everyone who reviewed pull requests, opened issues, participated in the design discussions, and requested features!
```

2018-10-22 22:02 UTC, gardrek commented on src/content/blog/release-0.9.md
> +Last release we made a list for planned features. While not all of them made it in this time you can be sure that we are still working on making them a reality as soon as possible. The major new feat
The start of this paragraph could be more clear. Is it talking about features listed for the last release or for this release? Just needs a bit of rewriting.

2018-10-22 22:03 UTC, gardrek reviewed
I finished adding my review comments.

2018-10-22 22:39 UTC, AnneKitsune approved these changes

2018-10-22 22:43 UTC, LucioFranco commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
This doesn't seem right to me

2018-10-22 22:47 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
Why?

2018-10-22 22:48 UTC, LucioFranco commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
Idk, just doesn't sound right to me 🤷‍♀️

2018-10-22 22:49 UTC, Moxinilian commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
glTF scene__s__ tho
it's the correct thing to say

2018-10-22 22:50 UTC, LucioFranco commented on src/content/blog/release-0.9.md
> +*   glTF scenes no longer has materials swapped around.
nvm, i guess saying it again this makes sense lol

2018-10-22 22:51 UTC, Moxinilian approved these changes
This will be ready to be merged as soon as 0.9 is published.
I will also update the docs page for 0.9

2018-10-22 22:52 UTC, Moxinilian commented
Never mind, it seems like Ellie did an excellent job: it will update automatically.

2018-10-23 04:18 UTC, randomPoison approved these changes
:shipit:

2018-10-23 04:40 UTC, jojolepro commented
do we have bors in here?
bors r+

2018-10-23 05:41 UTC, merged