Add twia12 and change structure
amethyst/website-legacy pull request #114
Opened 2018-10-24 19:49 UTC by torkleyy

WIP

2018-10-24 19:49 UTC, torkleyy commented on src/content/blog/twia-12.md
> +Hello and welcome to the 12 issue of _This Week in Amethyst_, a blog bringing to
```suggestion
Hello and welcome to the 12th issue of _This Week in Amethyst_, a blog bringing to
```

2018-10-24 20:03 UTC, torkleyy commented on src/content/blog/twia-12.md
> +title = "This week in Amethyst - 43/2018"
I prefer this format over numbering them from 1 to infinity.

2018-10-24 20:03 UTC, torkleyy commented on src/content/blog/twia-12.md
> +CI has is crucially important for projects, even more so for big ones. That
```suggestion
CI is crucially important for projects, even more so for big ones. That
```

2018-10-25 12:41 UTC, dotellie requested changes
Good job! I just have few things I would like to see changed.

2018-10-25 12:41 UTC, magnonellie commented on src/content/blog/twia-12.md
> +CI is crucially important for projects, even more so for big ones. That
```suggestion
CI is crucially important for any project, even more so for the big ones. That
```

2018-10-25 12:41 UTC, magnonellie commented on src/content/blog/twia-12.md
> +We're happy about the fast growing activity on our project! Given the wide
```suggestion
We're very proud of the fast growing activity on our project! Given the wide
```

2018-10-25 12:41 UTC, magnonellie commented on src/content/blog/twia-12.md
> +and `nalgebra` got a nice & easy API ([nalgebra-glm][nlg]), we're doing the
I'm not sure we should mention that API seeing as we aren't going to be using it internally in the engine. Your call though.

2018-10-25 12:41 UTC, magnonellie commented on src/content/blog/twia-12.md
> +and prefabs in Amethyst; soon we'll no longer have to format them by hand :)
```suggestion
and prefabs in Amethyst; soon we'll no longer have to format them by hand.
```

2018-10-25 12:41 UTC, magnonellie commented on src/content/blog/twia-12.md
> +[their own game][wil]. I'm posting a little proof of concept they showed us
You should get rid of the `I'm`

2018-10-25 12:43 UTC, torkleyy commented on src/content/blog/twia-12.md
> +and `nalgebra` got a nice & easy API ([nalgebra-glm][nlg]), we're doing the
Okay I just asked if we are using it ^^

2018-10-25 12:44 UTC, torkleyy commented on src/content/blog/twia-12.md
> +and prefabs in Amethyst; soon we'll no longer have to format them by hand :)
No smiley?

2018-10-25 12:44 UTC, torkleyy commented on src/content/blog/twia-12.md
> +[their own game][wil]. I'm posting a little proof of concept they showed us
Yeah, I'm not quite sure. I first tried to keep it impersonal. Let's be consistent here.

2018-10-25 12:45 UTC, magnonellie commented on src/content/blog/twia-12.md
> +and prefabs in Amethyst; soon we'll no longer have to format them by hand :)
I don't think we should have it since it comes off as a bit unprofessional, but this is only a suggestion after all :wink:

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
I'd say Travis has been doing a great job honestly. I don't want to put Travis and AppVeyor on the same level, because the former's service is way superior. I'd reformulate that into:
"Amethyst's workflow is extremely dependant on good Continuous Integration (or CI). It allows us to make sure all pull requests we merge pass all our tests, enabling us to expand fast. Travis, our free CI provider, has been doing a great job, but we needed faster and more parallel builds."

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +* use [Concourse][con] for building PRs and showing its status
```suggestion
* use [Concourse][con] as a first pass for building PRs for Linux and showing its status
```

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +* AppVeyor has been dropped entirely
```suggestion
* AppVeyor has been dropped entirely (because of the poor quality of its free service, it has now been entirely replaced thanks to Travis' new support for Windows)
```
I hate AppVeyor.

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +and `nalgebra` got a nice & easy API ([nalgebra-glm][nlg]), we're doing the
Are we really using `nalgebra-glm`?

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +to both historic and simplicity reasons. Since it's in maintainance mode now
Maintenance mode? I think you meant "may no longer be maintained".

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +We've decided that we want to move to Nalgebra. We previously used `cgmath` due
I know you like to get to the point, but this might be a bit rough lol
Maybe people don't know what nalgebra is.
"Amethyst's math library has always been `cgmath`. But blah blah blah, so we decided that we will now move to `nalgebra`", something along those lines.

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +"Std I/O driven application (aka `amethyst_commands`)" ([link][rfc]).
I love the idea of presenting RFCs!

2018-10-25 12:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w") }}
I'm not sure if this will render properly. Could you try rendering the website locally to see if it works well on desktop and mobile views?

2018-10-25 12:51 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +[tor]: https://github.com/torkleyy
Use the built-in authoring system. See Discord.

2018-10-25 12:51 UTC, torkleyy commented on src/content/blog/twia-12.md
> +* AppVeyor has been dropped entirely
Well, I don't think that needs to go in there.

2018-10-25 12:51 UTC, torkleyy commented on src/content/blog/twia-12.md
> +and `nalgebra` got a nice & easy API ([nalgebra-glm][nlg]), we're doing the
That's unresolved.

2018-10-25 12:51 UTC, torkleyy commented on src/content/blog/twia-12.md
> +to both historic and simplicity reasons. Since it's in maintainance mode now
Well, maintenance mode = I'm gonna merge PRs that come in.

2018-10-25 12:51 UTC, torkleyy commented on src/content/blog/twia-12.md
> +to both historic and simplicity reasons. Since it's in maintainance mode now
It's in rustgd now.

2018-10-25 12:52 UTC, torkleyy commented on src/content/blog/twia-12.md
> +"Std I/O driven application (aka `amethyst_commands`)" ([link][rfc]).
:+1: :smiley:

2018-10-25 12:52 UTC, torkleyy commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w") }}
I tried.

2018-10-25 12:53 UTC, torkleyy commented on src/content/blog/twia-12.md
> +[tor]: https://github.com/torkleyy
I just applied what the other editions had at the end. I'm not sure what you mean here.

2018-10-25 12:54 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +* AppVeyor has been dropped entirely
Alright

2018-10-25 12:54 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +and `nalgebra` got a nice & easy API ([nalgebra-glm][nlg]), we're doing the
I'm pretty sure we aren't.

2018-10-25 12:54 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +to both historic and simplicity reasons. Since it's in maintainance mode now
You should explain it then.

2018-10-25 12:55 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w") }}
Okay, have you checked there is no overflow?

2018-10-25 12:55 UTC, torkleyy commented on src/content/blog/twia-12.md
> +[tor]: https://github.com/torkleyy
Ah saw it.

2018-10-25 12:58 UTC, torkleyy commented on src/content/blog/twia-12.md
> +We've decided that we want to move to Nalgebra. We previously used `cgmath` due
Please check if you like it now.

2018-10-25 13:12 UTC, Moxinilian commented
Changes are good so far.

2018-10-25 13:34 UTC, Rhuagh commented on src/content/blog/twia-12.md
> +In other news, [Yuurai][yuu] is working a formatting tool for [RON files][ron]!
`is working on a formatting tool`

2018-10-25 13:34 UTC, Rhuagh commented on src/content/blog/twia-12.md
> +soem more input!
soem

2018-10-25 13:53 UTC, torkleyy commented on src/content/blog/twia-12.md
> +In other news, [Yuurai][yuu] is working a formatting tool for [RON files][ron]!
ah right

2018-10-25 14:26 UTC, LucioFranco requested changes
This is awesome!! but maybe we should add something about laminar? 😉

2018-10-25 14:26 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +and `nalgebra` got an easier API, we're doing the migration.
has an easier API, we're going to migrate Amethyst to `nalgebra`.

2018-10-25 14:26 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +and prefabs in Amethyst; soon we'll no longer have to format them by hand.
I think this deserves a `!` at the end 😄

2018-10-25 14:26 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +didn't work on Amethyst before.
especially if you have not worked on Amethyst before

2018-10-25 14:26 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +Thank you for helping the project to make progress!
Thank you for helping push the project forward!

to me this sounds better and the current phrase is a bit awkward.

2018-10-25 14:27 UTC, torkleyy commented
Oh right, laminar. Sorry, I haven't been following at all in the last days. Could you (net-devs) come up with a section / paragraph?

2018-10-25 14:28 UTC, torkleyy commented on src/content/blog/twia-12.md
> +and `nalgebra` got an easier API, we're doing the migration.
But nalgebra had a rather complex API before (due to many generics). The recent additions (non-generic versions) have made it easier.

2018-10-25 14:29 UTC, Moxinilian commented
Laminar is everywhere already. What about keeping it for next week?

2018-10-25 14:31 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +and `nalgebra` got an easier API, we're doing the migration.
I don't think that saying `has` removes that though. since technically that change was in the past

2018-10-25 14:31 UTC, LucioFranco commented
@fhaynes @TimonPost what do you think? Should we add something about `laminar`?

2018-10-25 14:32 UTC, Moxinilian commented
This would be especially in case we don't have anything to say next week. Going a bit more in depth with laminar.

2018-10-25 14:58 UTC, torkleyy commented on src/content/blog/twia-12.md
> +and `nalgebra` got an easier API, we're doing the migration.
now has?

2018-10-25 15:00 UTC, torkleyy commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w") }}
Done.

2018-10-25 15:13 UTC, torkleyy commented
![image](https://user-images.githubusercontent.com/23152057/47510881-55fbae00-d879-11e8-9a49-ba15fbc3d699.png)

2018-10-25 15:19 UTC, torkleyy commented
Squashed and comments addressed.

2018-10-25 15:23 UTC, Moxinilian commented
So what about my comments on the introduction of CI?

2018-10-25 15:29 UTC, torkleyy commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
Both CI services did cause us issues, the fact that we use Travis can be seen a couple lines beneath. I'm gonna add one sentence, give me a sec

2018-10-25 15:33 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +and `nalgebra` got an easier API, we're doing the migration.
what

2018-10-25 15:33 UTC, torkleyy commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
Fixed.

2018-10-25 15:36 UTC, LucioFranco approved these changes
👍 🎉

2018-10-25 15:39 UTC, dotellie approved these changes

2018-10-25 15:39 UTC, magnonellie commented on src/content/blog/twia-12.md
> +Speaking of prefabs.. [Rhuagh][rhu] is working on [a PR][prd] that lets us define
```suggestion
Speaking of prefabs... [Rhuagh][rhu] is working on [a PR][prd] that lets us define
```

2018-10-25 15:39 UTC, magnonellie commented on src/content/blog/twia-12.md
> +said, Travis and AppVeyor have been causing us issues since a long time,
```suggestion
said, Travis and AppVeyor have been causing us issues for some time now,
```

2018-10-25 15:39 UTC, magnonellie commented on src/content/blog/twia-12.md
> +There's one RFC I've chosen to present here,
I probably missed this when I first looked through, but I still don't think these post should ever refer to yourself. :stuck_out_tongue_closed_eyes:

2018-10-25 15:42 UTC, torkleyy commented on src/content/blog/twia-12.md
> +There's one RFC I've chosen to present here,
damn, and I thought I could get through with it.

2018-10-25 15:44 UTC, torkleyy commented on src/content/blog/twia-12.md
> +Speaking of prefabs.. [Rhuagh][rhu] is working on [a PR][prd] that lets us define
That sounds too long :P

2018-10-25 15:47 UTC, torkleyy commented on src/content/blog/twia-12.md
> +There's one RFC I've chosen to present here,
Okay make a suggestion please bc I know you're not gonna like my sentence.

2018-10-25 15:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
What I didn't like was the wording lol

2018-10-25 15:48 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
I don't really care about comparing AppVeyor and Travis.

2018-10-25 15:49 UTC, torkleyy commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
...

2018-10-25 15:50 UTC, torkleyy commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
You don't want to compare them but still you don't want to tell Travis has been causing issues even though it has?

Sorry, I'm not following anymore.

2018-10-25 15:56 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +There's one RFC I've chosen to present here,
🤣

2018-10-25 15:58 UTC, magnonellie commented on src/content/blog/twia-12.md
> +There's one RFC I've chosen to present here,
`Among the recently opened RFCs, theres is a particularly interesting one called "Std I/O driven application (aka `amethyst_commands`)"` and then I would have personally also added that it's written by Azriel at the end, but that doesn't work with the next paragraph as it's currently written.

2018-10-25 15:59 UTC, magnonellie commented on src/content/blog/twia-12.md
> +Speaking of prefabs.. [Rhuagh][rhu] is working on [a PR][prd] that lets us define
Well, two dots is never really allowed in the english language, but your call I guess :stuck_out_tongue:

2018-10-25 16:04 UTC, LucioFranco commented on src/content/blog/twia-12.md
> +Speaking of prefabs.. [Rhuagh][rhu] is working on [a PR][prd] that lets us define
Agreed should be three.

2018-10-25 16:07 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +blocking effective work on the engine due to long build times.
Whatever.

2018-10-25 16:18 UTC, torkleyy commented on src/content/blog/twia-12.md
> +Speaking of prefabs.. [Rhuagh][rhu] is working on [a PR][prd] that lets us define
Who said this post is written in English? I tend to use my personal fork (torkleyy/English).

Do you really want me to rebase?

2018-10-25 16:42 UTC, AnneKitsune reviewed
Very nice!
Just a couple of nitpicks.
Also, can you add an invite link to the discord server? :)

2018-10-25 16:42 UTC, jojolepro commented on src/content/blog/twia-12.md
> +and `nalgebra` has an easier API now, we're doing the migration.
> now and `nalgebra` has an easier API now

There's two "now" in the same sentence.

2018-10-25 16:42 UTC, jojolepro commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w", class="youtube") }}
Broken link on github preview, maybe it works fine once built?

2018-10-25 16:42 UTC, jojolepro commented on src/content/blog/twia-12.md
> +* [moderate] [Lighting / Pass compatibility][is3]
Is it working on since there's a new renderer in the works?
Also, is the new renderer still in the scope of 0.10? I didn't see any mentions.

2018-10-25 19:23 UTC, torkleyy commented on src/content/blog/twia-12.md
> +* [moderate] [Lighting / Pass compatibility][is3]
1) ?
2) No

2018-10-25 19:24 UTC, torkleyy commented on src/content/blog/twia-12.md
> +{{ youtube(id="jpk2MTeWz3w", class="youtube") }}
I tested it.

2018-10-25 19:28 UTC, jojolepro commented on src/content/blog/twia-12.md
> +* [moderate] [Lighting / Pass compatibility][is3]
1. I can't type. I meant, "is it worth working on since there's a new renderer being worked on".

If the renderer isn't in the score of 0.10 anymore, then it makes sense.
:+1:

2018-10-25 19:36 UTC, torkleyy commented
Yes, shaders are useful regardless of the renderer.

On Thu, Oct 25, 2018, 21:28 Joël Lupien <notifications@github.com> wrote:

> *@jojolepro* commented on this pull request.
> ------------------------------
>
> In src/content/blog/twia-12.md
> <https://github.com/amethyst/website/pull/114#discussion_r228305092>:
>
> > +## Call for participation
> +
> +We love contributions from the community, so if you see something you'd like
> +to work on, don't hesitate! We are going to help you and point you into the
> +right direction if something doesn't work out at first.
> +
> +We have tasks with different difficulty. Make sure to choose easier ones at
> +first, because hard issues can become quite frustrating, especially if you
> +haven't worked on Amethyst before.
> +
> +Here are seven issues for you to pick from:
> +
> +* [very easy] [Use the Transform component for all examples][is0]
> +* [easy] [Doc improvements][is1] (you can add new suggestions or fix existing)
> +* [easy] [Textures are dynamic unconditionally][is2]
> +* [moderate] [Lighting / Pass compatibility][is3]
>
>
>    1. I can't type. I meant, "is it worth working on since there's a new
>    renderer being worked on".
>
> If the renderer isn't in the score of 0.10 anymore, then it makes sense.
> 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/amethyst/website/pull/114#discussion_r228305092>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AWFFuW7bEhqlh5yGESKVscbck0nifHoSks5uohDYgaJpZM4X4ssM>
> .
>

2018-10-25 19:36 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +* [moderate] [Lighting / Pass compatibility][is3]
I wasn't aware of it not being in the 0.10 version?

2018-10-25 19:40 UTC, torkleyy commented
Rendering rewrites take time, and we wanted to have more regular releases.

On Thu, Oct 25, 2018, 21:36 Théo Degioanni <notifications@github.com> wrote:

> *@Moxinilian* commented on this pull request.
> ------------------------------
>
> In src/content/blog/twia-12.md
> <https://github.com/amethyst/website/pull/114#discussion_r228307545>:
>
> > +## Call for participation
> +
> +We love contributions from the community, so if you see something you'd like
> +to work on, don't hesitate! We are going to help you and point you into the
> +right direction if something doesn't work out at first.
> +
> +We have tasks with different difficulty. Make sure to choose easier ones at
> +first, because hard issues can become quite frustrating, especially if you
> +haven't worked on Amethyst before.
> +
> +Here are seven issues for you to pick from:
> +
> +* [very easy] [Use the Transform component for all examples][is0]
> +* [easy] [Doc improvements][is1] (you can add new suggestions or fix existing)
> +* [easy] [Textures are dynamic unconditionally][is2]
> +* [moderate] [Lighting / Pass compatibility][is3]
>
> I wasn't aware of it not being in the 0.10 version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/amethyst/website/pull/114#discussion_r228307545>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AWFFuR8JRqjNrhJWuhRh8kHwZFiuJiL1ks5uohLQgaJpZM4X4ssM>
> .
>

2018-10-26 16:28 UTC, Moxinilian commented on src/content/blog/twia-12.md
> +* [very easy] [Use the Transform component for all examples][is0]
amethyst/amethyst#1070 addressed this, don't forget to remove it

2018-10-27 11:15 UTC, LucioFranco approved these changes
LGTM! Thanks!

2018-10-27 12:57 UTC, torkleyy commented
Thank you for all the reviews!
bors r+

2018-10-27 13:18 UTC, merged