Updated to new design
amethyst/website-legacy pull request #141
Opened 2019-02-08 01:19 UTC by piedoom

Buildscripts should work but I don't know about CI

2019-02-08 01:20 UTC, piedoom commented on src/config.toml
> +discord_invite = "https://discord.gg/E2Dd244"
I'm not sure why we ditched the vanity URL in the new repo - i just copied it over. we can bring it back if we need to.

2019-02-08 02:57 UTC, LucioFranco commented on src/config.toml
> +discord_invite = "https://discord.gg/E2Dd244"
We should bring it back, I assume the last time the new site was touched was before we got the nice url.

2019-02-08 03:04 UTC, LucioFranco requested changes
Overall looking good, just a few updates, I think there is just a bunch of old stuff.

2019-02-08 03:04 UTC, LucioFranco commented on README.md
> +[di]: https://discord.gg/GnP5Whs
this should also be updated

2019-02-08 03:04 UTC, LucioFranco commented on README.md
> +$ cd src && zola serve
we should just tell people to use quick_build and have it serve

2019-02-08 03:04 UTC, LucioFranco commented on generate.sh
> +zola_release="v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
can we make this so it can figure out the arch for the system its being run on? That way people on mac and windows can run this

2019-02-08 03:04 UTC, LucioFranco commented on generate.sh
> +cargo doc --all;
we need to revert this to the commands we had before

2019-02-08 03:04 UTC, LucioFranco commented on generate.sh
> +cargo doc --all;
same here

2019-02-08 03:04 UTC, LucioFranco commented on src/config.toml
> +base_url = "https://amethyst-engine.org"
this needs to be `amethyst.rs`

2019-02-08 03:04 UTC, LucioFranco commented on src/config.toml
> +latest_release_tag = "0.10.0"
hmm I thought we had found a way to avoid having to do this @Moxinilian do you remember?

2019-02-08 03:04 UTC, LucioFranco commented on src/content/blog/dev-news-10-2018.md
> +As you might have seen [on Discord already](https://discord.gg/GnP5Whs), we've created
yup we should update these

2019-02-08 03:04 UTC, LucioFranco commented on src/content/sponsors.md
> -template = "sponsors.html"
si there a reason this is removed?

2019-02-08 04:13 UTC, piedoom commented on src/content/sponsors.md
> -template = "sponsors.html"
There's no longer a sponsors template in the new site repo.  I'll take a look and make sure it wasn't something that was made on the old site and never ported over.

2019-02-08 04:13 UTC, piedoom commented on src/config.toml
> +discord_invite = "https://discord.gg/E2Dd244"
Sounds good, will do that.

2019-02-08 04:17 UTC, piedoom commented on README.md
> +$ cd src && zola serve
`./quick_build.sh` is equivalent to `zola build`, not `zola serve` and is therefore not suitable for a local development workflow.  [We actually talked about this one briefly before :)](https://github.com/amethyst/website/pull/125#discussion_r234700512)

We could add a parameter for the script to add functionality but IMO at that point it's easier to just say `cd` and `serve`.

2019-02-08 04:18 UTC, piedoom commented on generate.sh
> +zola_release="v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
I can try my hand at it.  Do you prefer that to be in this PR or in a separate issue?

2019-02-08 04:21 UTC, piedoom commented on src/config.toml
> +base_url = "https://amethyst-engine.org"
If I understand correctly, `amethyst.rs` will not have anything besides a record pointing to `amethyst-engine.org`, where this site will live after being published.  Am I missing something there?

2019-02-08 04:22 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
If this is referencing a release on GH, Zola has support for fetching remote data which can be used to access the public GH API and find the latest release tag.  I'll look into how this is used and circle back.

2019-02-08 04:33 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
Yes, we can do this :D  

https://api.github.com/repos/amethyst/amethyst/releases

looks to be in chronological order so all we need to do is data[0].tag_name

2019-02-08 08:59 UTC, Moxinilian commented on generate.sh
> +zola_release="v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
I think having it in this PR will be good

2019-02-08 09:00 UTC, Moxinilian commented on src/config.toml
> +base_url = "https://amethyst-engine.org"
Why drop "www."?

2019-02-08 09:01 UTC, Moxinilian commented on src/config.toml
> +latest_release_tag = "0.10.0"
I think Ellie made a script that parses the source and insert the correct version. But your solution seems much better.

2019-02-08 09:02 UTC, Moxinilian commented on src/content/sponsors.md
> -template = "sponsors.html"
The sponsors are now on the donation page I believe.

2019-02-08 09:06 UTC, Moxinilian commented on src/content/sponsors.md
> -template = "sponsors.html"
Ah actually it seems like it’s not. Maybe we could have it on the landing page even then, it looks cool.

2019-02-08 09:39 UTC, distransient commented
Returns a 404 when you click the "about" button under "Foundation" in the footer

2019-02-08 16:27 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
True.  I *do* like the parsing script because it doesn't rely as heavily on GH... but I guess that's somewhat moot since we're relying on GH Pages in the first place.  In any case I think that would be appropriate in a separate PR if you both agree.

2019-02-08 21:58 UTC, khionu commented on src/config.toml
> +base_url = "https://amethyst-engine.org"
Making note of what was concluded on Discord, the site will be on `amethyst.rs`.

2019-02-09 22:04 UTC, piedoom commented on generate.sh
> +zola_release="v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
Update on this: I've realized that it is not reasonable to assume that Windows users will have bash installed.  I recommend that we use a PowerShell script in the future as commented in #142. 

I've added detection for mac, linux, win, and "other".  Linux is unchanged, Mac should now download the correct release, Windows now says the script is in progress of being written, and other OSs show a non-supported message.

I think for this PR we should be fine with only *nix support, since the 99% usecase as far as I can tell is for CI - most users will just `zola serve`.

2019-02-09 22:11 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
OK so looking in the `generate.sh` script, we have this line: 

`find . -name "*.html" -type f -exec sed -i 's/##LATEST_RELEASE_TAG##/'"$LATEST_TAG"'/g' '{}' \;`

Which searches for the `##LATEST_RELEASE_TAG##` string to replace with 

`LATEST_TAG=$(git describe --abbrev=0 --tags)`

I like this since it will be accurate on local systems, or when GH is unavailable for whatever reason.  However, I believe we exclusively use the version when linking to GH (search for `latest_release_tag` in the project).  So it may be a better and less complex choice to just use GH's public API.

2019-02-09 22:17 UTC, piedoom commented on src/content/sponsors.md
> -template = "sponsors.html"
I agree @Moxinilian - it seems like that info was omitted.  It would make sense on the homepage, perhaps under the "free with very permissive usage" section.

2019-02-09 22:21 UTC, piedoom commented
It looks as though we don't currently have an about page on the older site either.

We could either nix it for now and add it in once we have enough info to put there, or alternatively we could link to the wiki or the contributors page on GitHub.

2019-02-09 22:23 UTC, Moxinilian commented on generate.sh
> +# Copy the 404 static file to a specific location since Zola has some trouble with 404 pages
When I made this, it wasn't really an issue with Zola but more of a requirement from GitHub Pages to have a "/404.html" page as a fallback.

2019-02-09 22:25 UTC, distransient commented
Nixing it is fine. Just having it be a link to the home page, which is itself a bit of an "about" works fine in the meantime too.

2019-02-09 22:26 UTC, piedoom commented on generate.sh
> +# Copy the 404 static file to a specific location since Zola has some trouble with 404 pages
Ah, my bad.  I recalled that Zola had issues with 404 pages but was unaware of the Github requirement.  I will revert that comment to make sure it isn't misleading.

2019-02-10 09:43 UTC, piedoom commented on README.md
> +$ cd src && zola serve
Marking as resolved for now, please re-open if you would prefer I do something else here

2019-02-10 09:57 UTC, piedoom commented on generate.sh
>  find . -name "*.html" -type f -exec sed -i 's/##LATEST_RELEASE_TAG##/'"$LATEST_TAG"'/g' '{}' \;
This is breaking on MacOS - `sed: 1: "./doc/master/amethyst_c ...": invalid command code .`

Apparently this is a [mac sed implementation issue.](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux).  I will impl an OS specific check before running the command for mac

2019-02-10 09:58 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
I also need to make sure this isn't also used outside the website such as in mdbook.

2019-02-10 10:02 UTC, piedoom commented on generate.sh
> +zola_release="v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
with af462d2 this should be good to go

2019-02-10 10:03 UTC, piedoom commented on src/config.toml
> +latest_release_tag = "0.10.0"
Resolving in favor of creating a separate issue/pr in the future.

2019-02-10 10:04 UTC, piedoom commented on generate.sh
>  find . -name "*.html" -type f -exec sed -i 's/##LATEST_RELEASE_TAG##/'"$LATEST_TAG"'/g' '{}' \;
Fixed in 9cd4cf5

2019-02-10 10:21 UTC, piedoom commented on src/content/sponsors.md
> -template = "sponsors.html"
This has been added - here's a preview image.  We can make it look a bit more polished later but for now I think it looks fine

![image](https://user-images.githubusercontent.com/8846211/52532458-39ca3280-2ceb-11e9-8d36-e85d971afbfa.png)

2019-02-10 10:29 UTC, piedoom commented
About page is removed for now.

2019-02-10 18:02 UTC, merged