New website
amethyst/website-legacy pull request #60
Opened 2017-07-17 02:42 UTC by Aceeri

Looks better than my old crappy css/html 👍

2017-07-17 05:27 UTC, LucioFranco commented
@Aceeri did you add all the source code for semantic? there are a lot of CSS files.

2017-07-17 06:39 UTC, Aceeri commented
@LucioFranco Yeah, planning on pruning them all to just using the minify one, since I'm not really using anything else.

2017-07-18 13:58 UTC, LucioFranco commented
@Aceeri I like it is there a reason the lists of TWIA are not centered?

2017-07-18 15:05 UTC, ebkalderon requested changes
Overall, this looks pretty damn good! Much better than our existing website. Besides a few nits to address, I have a few more comments:

1. The light blue link color doesn't work too well with the purple/navy-blue color palette. I would recommend changing it to either a purple, lavender, or similar color.
2. In the `doc` page, you should probably replace the simple left-aligned bulleted list with two columns labeled **Learn** and **References**, respectively. If you can find some nice looking black symbolic icons to accompany this, it would be even better.

2017-07-18 15:05 UTC, ebkalderon commented on .gitignore
> +/book/
The preceding slashes aren't necessary for these lines.

2017-07-18 15:05 UTC, ebkalderon commented on src/_layouts/default.liquid
> -  </script>
It would be nice to add the Gitter chat sidecar back in, at least for non-mobile users if possible. It directs people to one of our central hubs of activity and encourages conversation.

The Gitter link already present at the bottom of the page should remain regardless, though.

2017-07-18 20:40 UTC, Aceeri commented on .gitignore
> +/book/
Sorry, became a bit of a habit from previous projects.

2017-07-18 20:41 UTC, Aceeri commented on src/_layouts/default.liquid
> -  </script>
I have a page "dedicated" to gitter that just uses an <iframe> tag for the chat, I'll re-add the sidecar, but I'd prefer if the style of the button and such was left more to us (since the little bubble-y button looks a bit out of place.

2017-07-18 20:46 UTC, Aceeri commented
@LucioFranco I was thinking of adding a second column there with maybe "Changelogs" or something? If anyone has ideas for that, it would help out. (For now I could always just remove that second column so the news is centered)

@ebkalderon 
1. I'll try to get find a good lighter purple or something for it.
2. I was trying to think of a better name for them, "References" seems to work a lot better. :+1:

2017-07-18 21:17 UTC, ebkalderon commented on src/_layouts/default.liquid
> -  </script>
Interesting, I didn't know you had a dedicated page to Gitter. Is it linked to anywhere on the site?

2017-07-18 21:18 UTC, ebkalderon commented on .gitignore
> +/book/
No worries. Thank you! 👍

2017-07-18 21:19 UTC, Aceeri commented on src/_layouts/default.liquid
> -  </script>
Not yet, I was just testing it to see if it would work.

2017-07-18 21:23 UTC, ebkalderon commented
@Aceeri I would also suggest fleshing out the text summary on the homepage into a hero image of sorts with a splash of color and button-style links to **What is it?** (could link to a features page or something) and **Get it now** (links to Crates.io page).

My own new website prototype from a few months back (https://www.eyalkalderon.com/) has a hero banner like that on the homepage, and I think it might make the homepage "pop" better IMO.

2017-09-08 04:17 UTC, merged