[WIP] Publish "This Year in Amethyst 10"
amethyst/website-legacy pull request #67
Opened 2017-09-16 12:03 UTC by nchashch

2017-09-16 12:15 UTC, nchashch commented
TWiA 9 is actually more outdated than I thought, it was published before transform system was added, before `amethyst_context` was removed, before any kind of asset management was added.

I guess it would be ok to just say "Amethyst's design was drastically changed since TWiA9.", "We first added and then rewritten asset management.", "We have added the transform system."

2017-09-16 14:16 UTC, torkleyy commented on src/_posts/2017-09-16-twia-10.md
> +* Renderer was completely rewritten by [@eyalkalderon](ek)
with help by @omni-viral

2017-09-16 14:16 UTC, torkleyy commented on src/_posts/2017-09-16-twia-10.md
> +## New contributors
New members would also be nice

2017-09-16 17:18 UTC, LucioFranco commented on src/_posts/2017-09-16-twia-10.md
> +[ep]: https://github.com/amethyst/amethyst/pulls?q=is:pr+closed:YYYY-MM-DD..YYYY-MM-DD
That should be the link that works for the engine `https://github.com/amethyst/amethyst/pulls?q=is:pr+closed:2016-09-11..2017-09-16` and I would remove the tools, as there has been no activity in that repo all year.

2017-09-16 17:29 UTC, LucioFranco requested changes
This is good still a bit more content and I think we can give it a final review and publish it. Thanks @nchashch

2017-09-16 17:29 UTC, LucioFranco commented on src/_posts/2017-09-16-twia-10.md
> +now we have better design and data parallel rendering.
I think this should be parallel data rendering?

2017-09-16 17:29 UTC, LucioFranco commented on src/_posts/2017-09-16-twia-10.md
> +
I know there are some more notable changes so we should add all of the big ones, like transform etc. 😄

2017-09-16 17:31 UTC, LucioFranco commented on src/_posts/2017-09-16-twia-10.md
> +## New contributors
I agree, section to just congratulate the new members would be nice since they are the ones that have kept this project going! 👍

2017-09-16 18:17 UTC, Xaeroxe commented on src/_posts/2017-09-16-twia-10.md
> +* Audio support was added by [@Xaeroxe](xr)
This made it into 0.5 so we can add it in the Announcements section I think.

2017-09-22 20:05 UTC, Aceeri commented on src/_posts/2017-09-16-twia-10.md
> +* [csherratt](https://github.com/csherratt)
@csherratt was actually around since pretty much the beginning, same with @msiglreith

2017-09-23 15:37 UTC, LucioFranco commented
@nchashch are you around to finish this or would you be looking to pass this off?

2017-10-03 14:52 UTC, Xaeroxe commented
@torkleyy @LucioFranco @Aceeri I believe I've addressed all review comments and finalized the post, can you give this one more review before we publish it?

2017-10-03 14:57 UTC, Rhuagh approved these changes

2017-10-03 15:51 UTC, LucioFranco approved these changes
LGTM

2017-10-03 16:16 UTC, Xaeroxe commented
Hey @amethyst/engine-devs Did I miss anyone on my new contributors list?

2017-10-03 17:28 UTC, torkleyy approved these changes

2017-10-03 17:35 UTC, merged

2017-10-03 17:41 UTC, kvark commented
@Xaeroxe you can still make it into TWIR if you are fast enough?

2017-10-03 18:57 UTC, Xaeroxe commented
I've posted my comment on the weekly thread, we'll see what happens.

2017-10-03 19:20 UTC, kvark commented
@Xaeroxe which thread? the proper way to get into TWIR is making a PR for https://github.com/cmr/this-week-in-rust/blob/master/drafts/2017-10-03-this-week-in-rust.md

2017-10-03 19:27 UTC, Xaeroxe commented
Oh, I just commented on the thread from r/rust.  I'll make a PR there too.

2017-10-03 19:45 UTC, Xaeroxe commented
Just a heads up: We made it into This Week in Rust

2017-10-04 06:51 UTC, Emilgardis commented
Woo! 🎉 

Just a little nitpick, shouldn't the list of announcements be tabulated?