Write first 2018 post!
amethyst/website-legacy pull request #82
Opened 2018-01-06 18:51 UTC by Xaeroxe

2018-01-06 19:19 UTC, Rhuagh approved these changes

2018-01-07 09:45 UTC, torkleyy requested changes

2018-01-07 09:45 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +- 2D texture animation is in progress in [#505][505] by [@Xaeroxe][xr] this
I think you want to make this two sentences.

2018-01-07 09:45 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +- A rewrite of the renderer in [#463][463] to use the upcoming gfx hal is going to allow our
Could link to `gfx_hal`

2018-01-07 09:45 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +### Notable additions
Here it says notable additions, but you're mostly listing current PRs.

2018-01-07 09:45 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +### Notable additions
It would be good to list the major changes here, that's quite helpful for people just watching the project.

2018-01-07 22:37 UTC, Xaeroxe commented
@torkleyy Updated with a lot more content.

2018-01-10 18:54 UTC, Xaeroxe commented
r? @torkleyy 

Waiting for your review to publish this.

2018-01-12 11:16 UTC, torkleyy commented
Sorry, reviewing it now.

2018-01-12 11:20 UTC, torkleyy approved these changes
One small nit, feel free to ignore it. r=me when you're happy :)

2018-01-12 11:20 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +more mentors!  If you'd like to volunteer please let us know on [#412][412]
Missing full stop

2018-01-12 11:20 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +### Notable additions
You added a nice summary, that looks really great :) Thank you!

2018-01-12 11:20 UTC, torkleyy commented on src/_posts/2018-01-06-blog.md
> +While we don't have any specific calls for participation this post please never
Not a blocker for this post, but it would be good to create nice issues that can be tackled by new contributors (so a good description of the task needs to be included).

2018-01-12 15:28 UTC, Xaeroxe commented
bors r+

2018-01-12 15:51 UTC, merged